/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse0 0x00u /*!<@brief Drive Strength Enable: Low */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_INV_inv0 0x00u /*!<@brief Invert Input: Does not invert */
#define PCR_ODE_ode0 0x00u /*!<@brief Open Drain Enable: Disables */
#define PCR_PE_pe0 0x00u   /*!<@brief Pull Enable: Disables */
#define PCR_PFE_pfe0 0x00u /*!<@brief Passive Filter Enable: Disables */
#define PCR_PS_ps0 0x00u   /*!<@brief Pull Select: Enables internal pulldown resistor */
#define PCR_SRE_sre0 0x00u /*!<@brief Slew Rate Enable: Fast */

/*! @name PORT3_6 (number 44), PWM_DIM9
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM9_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM9_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM9_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT3_7 (number 43), PWM_DIM5
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM5_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM5_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM5_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT3_10 (number 40), PWM_DIM7
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM7_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM7_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM7_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_14 (number 36), PWM_DIM1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM1_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM1_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_9 (number 41), PWM_DIM8
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM8_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM8_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM8_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT3_11 (number 39), PWM_DIM2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM2_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM2_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_8 (number 42), INH_DIM_7u8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INH_DIM_7u8_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INH_DIM_7u8_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INH_DIM_7u8_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INH_DIM_7u8_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INH_DIM_7u8_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INH_DIM_7u8_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORT3_12 (number 38), PWM_DIM10
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM10_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM10_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM10_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORT3_13 (number 37), PWM_DIM6
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_PWM_DIM6_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_PWM_DIM6_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_PWM_DIM6_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_15 (number 35), INH_DIM_1u2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INH_DIM_1u2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INH_DIM_1u2_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INH_DIM_1u2_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INH_DIM_1u2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INH_DIM_1u2_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INH_DIM_1u2_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
