/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SysTick */
/* Definition of clock source frequency. */
#define SYSTICK_CLK_FREQ 12000000UL
/* Definition of clock source frequency. */
#define SYSTICK_TICKS 12000000UL
/* SysTick interrupt vector ID (number). */
#define SYSTICK_TIMER_REFERENCE_IRQN SysTick_IRQn
/* SysTick interrupt handler identifier. */
#define SysTick_Handler SysTick_Handler
/* Alias for GPIO0 peripheral */
#define GPIO0_GPIO GPIO0

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
