/*
 * deviceConfig.h
 *
 *  Created on: 17.01.2026
 *      Author: lukas
 */

#ifndef DEVICECONFIG_H_
#define DEVICECONFIG_H_
#include "relay_ctrl.h"

#define A3


#ifdef A1
#define DEVICE_ADDRESS 0x1
#define RELAY_TYPE_R1 SWITCH
#define RELAY_TYPE_R2 SWITCH
#define RELAY_TYPE_R3 SWITCH
#define RELAY_TYPE_R4 SWITCH
#define RELAY_TYPE_R5 SWITCH
#define RELAY_TYPE_R6 SWITCH
#define RELAY_TYPE_R7 SWITCH
#define RELAY_TYPE_R8 SWITCH
#define RELAY_TYPE_R9 SWITCH

#endif

#ifdef A2
#define DEVICE_ADDRESS 0x2
#define RELAY_TYPE_R1 BLINDS_UP
#define RELAY_TYPE_R2 BLINDS_DOWN
#define RELAY_TYPE_R3 BLINDS_UP
#define RELAY_TYPE_R4 BLINDS_DOWN
#define RELAY_TYPE_R5 BLINDS_UP
#define RELAY_TYPE_R6 BLINDS_DOWN
#define RELAY_TYPE_R7 BLINDS_UP
#define RELAY_TYPE_R8 BLINDS_DOWN
#define RELAY_TYPE_R9 SWITCH
#endif

#ifdef A3
#define DEVICE_ADDRESS 0x3
#define RELAY_TYPE_R1 BLINDS_UP
#define RELAY_TYPE_R2 BLINDS_DOWN
#define RELAY_TYPE_R3 BLINDS_UP
#define RELAY_TYPE_R4 BLINDS_DOWN
#define RELAY_TYPE_R5 BLINDS_UP
#define RELAY_TYPE_R6 BLINDS_DOWN
#define RELAY_TYPE_R7 BLINDS_UP
#define RELAY_TYPE_R8 BLINDS_DOWN
#define RELAY_TYPE_R9 SWITCH
#endif

#ifdef A4
#define DEVICE_ADDRESS 0x4
#define RELAY_TYPE_R1 BLINDS_UP
#define RELAY_TYPE_R2 BLINDS_DOWN
#define RELAY_TYPE_R3 BLINDS_UP
#define RELAY_TYPE_R4 BLINDS_DOWN
#define RELAY_TYPE_R5 BLINDS_UP
#define RELAY_TYPE_R6 BLINDS_DOWN
#define RELAY_TYPE_R7 BLINDS_UP
#define RELAY_TYPE_R8 BLINDS_DOWN
#define RELAY_TYPE_R9 SWITCH
#endif

#ifdef A5
#define DEVICE_ADDRESS 0x5
#define RELAY_TYPE_R1 BLINDS_UP
#define RELAY_TYPE_R2 BLINDS_DOWN
#define RELAY_TYPE_R3 BLINDS_UP
#define RELAY_TYPE_R4 BLINDS_DOWN
#define RELAY_TYPE_R5 BLINDS_UP
#define RELAY_TYPE_R6 BLINDS_DOWN
#define RELAY_TYPE_R7 BLINDS_UP
#define RELAY_TYPE_R8 BLINDS_DOWN
#define RELAY_TYPE_R9 SWITCH
#endif


#endif /* DEVICECONFIG_H_ */
