/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR0_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR12_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT2_PCR13_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT2_PCR16_MUX_mux11 0x03u /*!<@brief Pin Multiplex Control: Alternative 3 (chip-specific) */
#define PORT2_PCR1_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR7_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR29_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR30_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR31_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT3_PCR7_MUX_mux101 0x05u /*!<@brief Pin Multiplex Control: Alternative 5 (chip-specific) */

/*! @name PORT3_15 (number 35), INH_DIM_1u2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INH_DIM_1u2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_1u2_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_INH_DIM_1u2_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INH_DIM_1u2_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INH_DIM_1u2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_1u2_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INH_DIM_1u2_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_29 (number 32), INH_DIM_7u8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INH_DIM_7u8_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_7u8_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_INH_DIM_7u8_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INH_DIM_7u8_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INH_DIM_7u8_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_7u8_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INH_DIM_7u8_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_30 (number 31), Relay_K7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K7_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K7_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K7_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K7_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K7_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K7_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K7_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_31 (number 30), Relay_K5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K5_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K5_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K5_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K5_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K5_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K5_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K5_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT2_7 (number 21), Relay_K4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K4_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K4_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K4_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K4_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K4_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K4_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K4_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_3 (number 17), ADC_IN1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_2 (number 16), INH_DIM_3u4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INH_DIM_3u4_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_3u4_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_INH_DIM_3u4_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INH_DIM_3u4_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INH_DIM_3u4_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_3u4_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INH_DIM_3u4_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT2_1 (number 15), ADC_IN2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_IN2_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_IN2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_IN2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_0 (number 14), PCB_Temperature
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PCB_Temperature_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PCB_Temperature_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PCB_Temperature_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORT1_13 (number 7), Relay_K1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K1_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K1_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K1_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K1_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_12 (number 6), Relay_K9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K9_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K9_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K9_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K9_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K9_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K9_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K9_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_10 (number 4), Relay_K6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K6_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K6_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K6_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K6_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K6_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K6_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K6_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_9 (number 3), Relay_K2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K2_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K2_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K2_GPIO_PIN 9U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K2_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_8 (number 2), Relay_K3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K3_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K3_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K3_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K3_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K3_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K3_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K3_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_7 (number 1), RS485_nRE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_nRE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_nRE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RS485_nRE_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RS485_nRE_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS485_nRE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_nRE_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS485_nRE_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_8 (number 42), INH_DIM_5u6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INH_DIM_5u6_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_5u6_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_INH_DIM_5u6_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_INH_DIM_5u6_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_INH_DIM_5u6_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_INH_DIM_5u6_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_INH_DIM_5u6_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT1_6 (number 64), RS485_DE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_DE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_DE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RS485_DE_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RS485_DE_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS485_DE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_DE_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS485_DE_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_11 (number 5), Relay_K8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Relay_K8_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Relay_K8_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Relay_K8_GPIO_PIN 11U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Relay_K8_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Relay_K8_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Relay_K8_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Relay_K8_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_0 (number 46), FAN_Out
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FAN_Out_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_FAN_Out_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_FAN_Out_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_FAN_Out_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FAN_Out_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FAN_Out_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
